services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    command: flask run